### ISSUE TITLE
Spreadsheet: Losing current edit on "Close"

### ISSUE THREAD

**Issue by dreua** [ONLYOFFICE/onlyoffice-humhub#24] opened 2020-10-23 15:57 UTC
### Steps to reproduce
- Open some spreadsheet (xlsx) from HumHub, "Edit Document"
- Click an empty cell and type something, do not press enter
- Click "Close"
- Open the same spreadsheet again.

### Expected results
- The last edit should be saved or closing the document should be prevented / issue a warning to save the last change.

### Actual results
- The last edit is lost

### Versions
Humhub 1.6.4
ONLYOFFICE Connector for HumHub 2.1.3.2

**Comment by dreua** [comment] 2021-03-19 18:13
This is still an issue, anything we can do about it?

**Comment by alexanderonlyoffice** [comment] 2021-04-09 15:50
@dreua, we managed to reproduce the issue and fixed it, but, unfortunately, some fixes are also required on the Document Server side. They will be added in version 6.4 of the Document Server that is approximately planned to be released in Summer 2021. Unfortunately, I cannot specify any time frames right now, as this version is in development. 

The reason is that there is no way to determine unsaved changes and no proper way to propagate events from within the iframe in the current version of the Document Server.

**Comment by LinneyS** [comment] 2021-04-12 06:13
https://github.com/ONLYOFFICE/web-apps/commit/84d357560ed950a395f1c6209a6acf8e593f8fd1

**Closed** 2022-03-05 09:31 UTC

**Comment by dreua** [comment] 2022-03-19 10:12
Thanks, that's much better UX-wise! :tada:
